/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSnippetsNewRouteImport } from './routes/_app/snippets/new'
import { Route as AppSnippetsSnippetIdRouteImport } from './routes/_app/snippets/$snippetId'
import { Route as AppSnippetsSnippetIdEditRouteImport } from './routes/_app/snippets/$snippetId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSnippetsNewRoute = AppSnippetsNewRouteImport.update({
  id: '/snippets/new',
  path: '/snippets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsSnippetIdRoute = AppSnippetsSnippetIdRouteImport.update({
  id: '/snippets/$snippetId',
  path: '/snippets/$snippetId',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsSnippetIdEditRoute =
  AppSnippetsSnippetIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppSnippetsSnippetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/explore': typeof AppExploreRoute
  '/auth/': typeof AuthIndexRoute
  '/snippets/$snippetId': typeof AppSnippetsSnippetIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/snippets/$snippetId/edit': typeof AppSnippetsSnippetIdEditRoute
}
export interface FileRoutesByTo {
  '/explore': typeof AppExploreRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/snippets/$snippetId': typeof AppSnippetsSnippetIdRouteWithChildren
  '/snippets/new': typeof AppSnippetsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/snippets/$snippetId/edit': typeof AppSnippetsSnippetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/snippets/$snippetId': typeof AppSnippetsSnippetIdRouteWithChildren
  '/_app/snippets/new': typeof AppSnippetsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/snippets/$snippetId/edit': typeof AppSnippetsSnippetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/auth/'
    | '/snippets/$snippetId'
    | '/snippets/new'
    | '/api/auth/$'
    | '/snippets/$snippetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/'
    | '/auth'
    | '/snippets/$snippetId'
    | '/snippets/new'
    | '/api/auth/$'
    | '/snippets/$snippetId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/explore'
    | '/_app/'
    | '/auth/'
    | '/_app/snippets/$snippetId'
    | '/_app/snippets/new'
    | '/api/auth/$'
    | '/_app/snippets/$snippetId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/snippets/new': {
      id: '/_app/snippets/new'
      path: '/snippets/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof AppSnippetsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets/$snippetId': {
      id: '/_app/snippets/$snippetId'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof AppSnippetsSnippetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets/$snippetId/edit': {
      id: '/_app/snippets/$snippetId/edit'
      path: '/edit'
      fullPath: '/snippets/$snippetId/edit'
      preLoaderRoute: typeof AppSnippetsSnippetIdEditRouteImport
      parentRoute: typeof AppSnippetsSnippetIdRoute
    }
  }
}

interface AppSnippetsSnippetIdRouteChildren {
  AppSnippetsSnippetIdEditRoute: typeof AppSnippetsSnippetIdEditRoute
}

const AppSnippetsSnippetIdRouteChildren: AppSnippetsSnippetIdRouteChildren = {
  AppSnippetsSnippetIdEditRoute: AppSnippetsSnippetIdEditRoute,
}

const AppSnippetsSnippetIdRouteWithChildren =
  AppSnippetsSnippetIdRoute._addFileChildren(AppSnippetsSnippetIdRouteChildren)

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSnippetsSnippetIdRoute: typeof AppSnippetsSnippetIdRouteWithChildren
  AppSnippetsNewRoute: typeof AppSnippetsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppIndexRoute: AppIndexRoute,
  AppSnippetsSnippetIdRoute: AppSnippetsSnippetIdRouteWithChildren,
  AppSnippetsNewRoute: AppSnippetsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
